spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://${USER_DB_HOST:payflow-pranavdeshmukh5454-95ff.h.aivencloud.com}:${USER_DB_PORT:21782}/${USER_DB_NAME:defaultdb}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${BREVO_SMTP_HOST:smtp-relay.brevo.com}
    port: ${BREVO_SMTP_PORT:587}
    username: ${BREVO_SMTP_USERNAME:9f2083001@smtp-brevo.com}
    password: ${BREVO_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # ── Kafka Consumer ───────────────────────────────────────────────────────────
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    properties:
      security.protocol: SSL
      ssl.truststore.type: PEM
      ssl.keystore.type: PEM
      receive.buffer.bytes: 65536
      send.buffer.bytes: 65536

    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
      properties:
        spring.json.trusted.packages: "com.pranav.notification_service.kafka.event"
        spring.json.use.type.headers: false
        fetch.max.bytes: 1048576
        max.partition.fetch.bytes: 524288

    listener:
      concurrency: 1
      auto-startup: true

server:
  port: ${NOTIFICATION_PORT:8084}
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

internal:
  api-key: ${INTERNAL_API_KEY:PranavDeshmukh}

notification:
  from-email: ${NOTIFICATION_FROM_EMAIL:pranavdeshmukh5454@gmail.com}
  from-name: ${NOTIFICATION_FROM_NAME:PayFlow}

swaggerURL: ${SWAGGER_URL:http://localhost:8080}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator-endpoints: false

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health