spring:
  application:
    name: merchant-service

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:mysql://${USER_DB_HOST:payflow-pranavdeshmukh5454-95ff.h.aivencloud.com}:${USER_DB_PORT:21782}/${USER_DB_NAME:defaultdb}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # ── Redis ──────────────────────────────────────────────────────────────────
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
      timeout: 2000ms
      connect-timeout: 2000ms 

  rabbitmq:
    addresses: ${RABBITMQ_URL}
    connection-timeout: 5000
    requested-heartbeat: 30
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0


server:
  port: ${MERCHANT_PORT:8082}
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

internal:
  api-key: ${INTERNAL_API_KEY:PranavDeshmukh}

swaggerURL: ${SWAGGER_URL:http://localhost:8080}

springdoc:
  api-docs:
    enabled: true

cache:
  merchant-credentials-ttl-minutes: 30
  merchant-ttl-minutes: 60

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health
