spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

server:
  port: ${EUREKA_PORT:8761}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health