version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: payflow-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: payflow-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: payflow-kafka-ui
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: payflow
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # ── Redis ──────────────────────────────────────────────────────────────────
  redis:
    image: redis:7.2-alpine
    container_name: payflow-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: payflow-redis-ui
    ports:
      - "6380:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis

  # ── Elasticsearch ──────────────────────────────────────────────────────────
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.8
#    container_name: payflow-elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false       # disabled for local dev
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#      - elasticsearch_data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:9.2.8
#    container_name: payflow-kibana
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  redis_data:
#  elasticsearch_data: